- name: Template notify.sh
  ansible.builtin.template:
    src: ./templates/notify.sh
    dest: "{{ app_path }}notify.sh"
    mode: "0755"
- name: Template failure-notification service
  become: true
  ansible.builtin.template:
    src: ./templates/failure-notification.service.j2
    dest: "/etc/systemd/system/failure-notification@{{ service_name }}.service"
    owner: root
    group: sudo
    mode: "0644"
