- name: Setup server from scratch
  hosts: servers
  vars:
    app_path: /home/{{ ansible_user }}/tankbusters/
    service_name: tankbusters
  vars_files:
    - vars.yaml
  tasks:
    - import_tasks: ./tasks/setup-build.yaml
    - import_tasks: ./tasks/configure-services.yaml
